server:
  port: 8001
spring:
  application:
    name: Study-Advertise
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.128:3306/edu_ad?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Luo@123456
eureka:
  client:
    service-url:
      # eureka server的路径
      defaultZone: http://localhost:7001/eureka/
    # 是否需要搜索服务信息
    fetch-registry: true
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
  instance:
    #使用ip注册，否则会使用主机名注册
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:@project.version@
